extends Node
@warning_ignore_start("unused_signal")

signal start_cooking(patty)
signal stop_cooking(patty)
signal patty_entered_bin(patty)
signal patty_exited_bin(patty)
signal camera_moved_up()
signal camera_moved_down()
signal order_system_activated()
signal order_system_deactivated()
signal order_added(newOrder)
signal order_submitted(order)
signal order_accepted(order)
signal order_denied()
